// <auto-generated />
using System;
using Hospital_Management_System_WinForm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System_WinForm.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417191828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorInternalTreatment", b =>
                {
                    b.Property<int>("InternalTreatmentTreatmentID")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorsDoctorID")
                        .HasColumnType("int");

                    b.HasKey("InternalTreatmentTreatmentID", "SupervisorsDoctorID");

                    b.HasIndex("SupervisorsDoctorID");

                    b.ToTable("DoctorInternalTreatments", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", b =>
                {
                    b.Property<int>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatientID");

                    b.ToTable("Patients", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Settings.SystemSettings", b =>
                {
                    b.Property<int>("SystemSettingsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemSettingsID"));

                    b.Property<decimal>("BaseStaffSalary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SystemSettingsID");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment", b =>
                {
                    b.Property<int>("TreatmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatmentID"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TreatmentID");

                    b.HasIndex("PatientID");

                    b.ToTable("Treatments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.ContractDoctor", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTreatmentCost")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("ContractDoctors", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.StaffDoctor", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("StaffDoctors", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.TraineeDoctor", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TrainingEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TrainingStartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("TraineeDoctors", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.ExternalPatient", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.ToTable("ExternalPatients", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient");

                    b.Property<bool>("IsDischarged")
                        .HasColumnType("bit");

                    b.ToTable("InternalPatients", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.ExternalTreatment", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment");

                    b.Property<int>("ClinicNumber")
                        .HasColumnType("int");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalPatientPatientID")
                        .HasColumnType("int");

                    b.Property<int?>("InternalPatientPatientID")
                        .HasColumnType("int");

                    b.HasIndex("DoctorID");

                    b.HasIndex("ExternalPatientPatientID");

                    b.HasIndex("InternalPatientPatientID");

                    b.ToTable("ExternalTreatments", (string)null);
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.InternalTreatment", b =>
                {
                    b.HasBaseType("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InternalPatientPatientID")
                        .HasColumnType("int");

                    b.HasIndex("InternalPatientPatientID");

                    b.ToTable("InternalTreatments", (string)null);
                });

            modelBuilder.Entity("DoctorInternalTreatment", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Treatments.InternalTreatment", null)
                        .WithMany()
                        .HasForeignKey("InternalTreatmentTreatmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", null)
                        .WithMany()
                        .HasForeignKey("SupervisorsDoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.ContractDoctor", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Doctors.ContractDoctor", "DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.StaffDoctor", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Doctors.StaffDoctor", "DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Doctors.TraineeDoctor", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Doctors.TraineeDoctor", "DoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.ExternalPatient", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Patients.ExternalPatient", "PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.Patient", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", "PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.ExternalTreatment", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Doctors.Doctor", "TreatingDoctor")
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.ExternalPatient", null)
                        .WithMany("ExternalTreatments")
                        .HasForeignKey("ExternalPatientPatientID");

                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", null)
                        .WithMany("ExternalTreatments")
                        .HasForeignKey("InternalPatientPatientID");

                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Treatments.ExternalTreatment", "TreatmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreatingDoctor");
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Treatments.InternalTreatment", b =>
                {
                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", null)
                        .WithMany("InternalTreatments")
                        .HasForeignKey("InternalPatientPatientID");

                    b.HasOne("Hospital_Management_System_WinForm.Domain.Entities.Treatments.Treatment", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Management_System_WinForm.Domain.Entities.Treatments.InternalTreatment", "TreatmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.ExternalPatient", b =>
                {
                    b.Navigation("ExternalTreatments");
                });

            modelBuilder.Entity("Hospital_Management_System_WinForm.Domain.Entities.Patients.InternalPatient", b =>
                {
                    b.Navigation("ExternalTreatments");

                    b.Navigation("InternalTreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
